version: "3.7"

services:
  webapi:
    build:
      context: ./
      dockerfile: src/Glue.Delivery.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9003:80
    restart: always